language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+browser-switch-android@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.3
    - android-28
script: ./gradlew --info clean lint test
after_success: ./deploy_snapshot.sh

