language: android
jdk: oraclejdk8
notifications:
  email:
    - external-ci-notifications+browser-switch-android@getbraintree.com
sudo: true
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-29.0.2
    - android-28
script: ./gradlew --info clean lint test
