language: android
jdk: oraclejdk8
sudo: true
android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
before_install:
  - yes | sdkmanager "platforms;android-30"
script: ./gradlew --info clean lint test

