name: Decode Signing Key
description: Decode GPG key into file
inputs:
  signing_key_file:
    description: Signing Key File
    required: true
    default: ''
  signing_file_path:
    description: 'Signing File Path'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
    - run: |
        echo "${{inputs.signing_key_file}}" > ~/secretKey.gpg.b64
        base64 -d ~/secretKey.gpg.b64 > ${{ inputs.signing_file_path }}
      shell: bash
