name: Static Analysis
on: [pull_request, workflow_dispatch]
concurrency:
  group: static-analysis-${{ github.event.number }}
  cancel-in-progress: true
jobs:
  android_lint:
    name: Android Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: ./.github/actions/setup_java_11
      - name: Lint
        run: ./ci android_lint
      - name: Set up Java 17
        uses: ./.github/actions/setup_java_17
      - name: Lint
        run: ./ci android_lint