name: Tests
on: [pull_request]
jobs:
  unit_test_job:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Java 11
        uses: ./.github/actions/setup_java_11
      - name: Unit Tests
        run: ./ci unit_tests
      - name: Set up Java 17
        uses: ./.github/actions/setup_java_17
      - name: Unit Tests
        run: ./ci unit_tests
